/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.techbooster.projetoagenda02.view;

import com.techbooster.projetoagenda02.controller.ControllerCompromissos;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author emesson
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menOpcoes = new javax.swing.JMenu();
        abrListaCompromissos = new javax.swing.JMenuItem();
        abrFormCompromisso = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        abrSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seja bem-vindo");

        menOpcoes.setText("Agenda");

        abrListaCompromissos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        abrListaCompromissos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda-24px.png"))); // NOI18N
        abrListaCompromissos.setText("Lista de compromisso");
        abrListaCompromissos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrListaCompromissosActionPerformed(evt);
            }
        });
        menOpcoes.add(abrListaCompromissos);

        abrFormCompromisso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        abrFormCompromisso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-compromisso-24px.png"))); // NOI18N
        abrFormCompromisso.setText("Adicionar Compromisso");
        abrFormCompromisso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrFormCompromissoActionPerformed(evt);
            }
        });
        menOpcoes.add(abrFormCompromisso);

        jMenuBar1.add(menOpcoes);

        jMenu2.setText("Opções");

        abrSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        abrSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair-24px.png"))); // NOI18N
        abrSair.setText("Sair");
        abrSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrSairActionPerformed(evt);
            }
        });
        jMenu2.add(abrSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(131, 131, 131))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrListaCompromissosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrListaCompromissosActionPerformed
        FormularioCompromisso fc = new FormularioCompromisso();
        fc.setModal(true);
        fc.setVisible(true);
    }//GEN-LAST:event_abrListaCompromissosActionPerformed

    private void abrFormCompromissoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrFormCompromissoActionPerformed
        AdicionarCompromisso ac = new AdicionarCompromisso();
        ac.setModal(true);
        ac.setVisible(true);
    }//GEN-LAST:event_abrFormCompromissoActionPerformed

    private void abrSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrSairActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja sair, meu patrão?")  == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_abrSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrFormCompromisso;
    private javax.swing.JMenuItem abrListaCompromissos;
    private javax.swing.JMenuItem abrSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menOpcoes;
    // End of variables declaration//GEN-END:variables
}
